# Generated by Django 5.1.3 on 2025-01-22 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articolo',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='giornalista',
            options={'verbose_name': 'Giornalista', 'verbose_name_plural': 'Giornalisti'},
        ),
        migrations.AddField(
            model_name='articolo',
            name='dataPubblicazione',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 22, 9, 19, 54, 497460)),
        ),
        migrations.AddField(
            model_name='articolo',
            name='visualizzazioni',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giornalista',
            name='dataNascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 1, 22, 9, 19, 54, 497460)),
        ),
    ]
