# Generated by Django 5.1.3 on 2025-02-12 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articolo_datapubblicazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='dataPubblicazione',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 39, 55, 791513)),
        ),
        migrations.AlterField(
            model_name='giornalista',
            name='dataNascita',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 9, 39, 55, 791513)),
        ),
    ]
