# Generated by Django 5.1.3 on 2025-03-19 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corsi_formazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corso',
            name='data_fine',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 19, 11, 33, 56, 953142)),
        ),
        migrations.AlterField(
            model_name='corso',
            name='data_inizio',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 3, 19, 11, 33, 56, 953142)),
        ),
    ]
